rename-command FLUSHALL ""
rename-command FLUSHDB ""
rename-command CONFIG ""

maxmemory 384mb

maxmemory-policy volatile-lru

appendonly yes
appendfsync everysec

save 900 1
save 300 10
save 60 10000

protected-mode yes
tcp-backlog 511
timeout 0
tcp-keepalive 300